### ISSUE TITLE
Error on yarn build

### ISSUE THREAD

**Issue by tzs34** [huy-nguyen/webpack-and-pdfkit#2]
Hello,

Thanks for putting this together but I get errors hen I do 
yarn
yarn build
Module not found: Error: Can't resolve 'fs'  for a number of modules

**Comment by huy-nguyen** [comment]
I can't reproduce the problem you desribed. I've just cloned the repo clean on my machine and ran `yarn` and then `yarn build` with no problem. Can you provide more info?

**Comment by olee** [comment]
Same for me - just downloaded the repo and run yarn / yarn build and it throwed exceptions:
```
ERROR in ./node_modules/brotli/dec/dictionary-browser.js
Module not found: Error: Can't resolve 'fs' in 'D:\user\desktop\webpack-and-pdfkit-master\node_modules\brotli\dec'
 @ ./node_modules/brotli/dec/dictionary-browser.js 2:9-22
 @ ./node_modules/brotli/dec/dictionary.js
 @ ./node_modules/brotli/dec/decode.js
 @ ./node_modules/brotli/decompress.js
 @ ./node_modules/fontkit/index.js
 @ ./node_modules/pdfkit/js/font.js
 @ ./node_modules/pdfkit/js/mixins/fonts.js
 @ ./node_modules/pdfkit/js/document.js
 @ ./src/index.js

ERROR in ./node_modules/fontkit/index.js
Module not found: Error: Can't resolve 'fs' in 'D:\user\desktop\webpack-and-pdfkit-master\node_modules\fontkit'
...

ERROR in ./node_modules/linebreak/src/linebreaker.js
Module not found: Error: Can't resolve 'fs' in 'D:\user\desktop\webpack-and-pdfkit-master\node_modules\linebreak\src'
...
```

**Comment by olee** [comment]
Oh it works now!
It was a platform issue - it does not work on windows because of the `/` in the regex.
It works with this test: `/node_modules[\/\\](pdfkit|brotli|fontkit|linebreak|png-js|unicode-properties)[\/\\].*\.js$/`
